#!/usr/bin/env python3

"""
    Sax-Client.run
    
    :copyright: (c) Dec 2017 by Daniel Santos.
    :license: BSD, see LICENSE for more details.
"""

import config
from app import app

if __name__ == '__main__':
    app.run(host=config.HOST, port=config.PORT, debug=config.DEBUG)
